baseurl = "https://nakagawa07.github.io/ACCELStars2/"
title = "ACCELStars2"
author = "Daniel Zaragoza (Danielkvist)"
googleAnalytics = ""
enableRobotsTXT = true
defaultContentLanguage = "ja"
languageCode = "ja-jp"
paginate = 3
publishDir = "docs"
canonifyurls = true


theme = "piercer"
themesDir = "themes/"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params]
    description = "Piercer is a fast and customizable theme for Hugo. Designed with a mobile-first philosophy and with accessibility in mind."
    favicon = "favicon.ico"
    logo = "images/head_logo.png"
    customCSS = ["/Users/nakagawamizuhime/Desktop/test-site/themes/css/custom.css"]

[params.postcss]
    postcss = false

[params.palette]
    text = "#282a36"
    background = "#fdfdfd"
    accent = "#fdfdfd"
    foreground = "#282a36"
    separator = "#6272a4"
    cyan = "#8be9fd"
    green = "#50fa7b"
    orange = "#ffb86c"
    pink = "#4b4b4b"
    purple = "#000"
    red = "#ff5555"
    yellow = "#f1fa8c"

[params.fontsizes]
    base = "1em"
    p = "1.25em"
    h4 = "1.563em"
    h3 = "1.953em"
    h2 = "2.441em"
    h1 = "3.052em"

[params.googlefonts]
    font = ""

[params.serviceWorker]
    enable = true

[params.header]
    show = true

[params.cta]
    show = true
    message = "Learn more!"
    link = "https://github.com/danielkvist/hugo-piercer-theme#readme"

[params.fa]
    disable = false
    kit = ""

[params.form]
    show = true
    netlify = false
    action = ""
    method = "POST"
    section = "Contact me!"
    disclaimer = "Elit anim sit labore tempor exercitation in ad cupidatat."
    inputNameName = "Name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your Name"
    inputEmailName = "Email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your Email"
    SubmitValue = ""



[params.date]
    format = "7. 2, 2006"

[params.social]
    twitter = "#"
    facebook = "#"
    github = "#"
    gitlab = "#"
    codepen = "#"
    instagram = "#"
    pinterest = "#"
    youtube = "#"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""
    rss = "#"

[params.copy]
    message = "ACCELStars, Inc. All rights reserved"



[params.notfound]
    message = ""